CREATE DATABASE IF NOT EXISTS convini CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'conviniuser'@'%' IDENTIFIED BY 'convinipass';
GRANT ALL PRIVILEGES ON convini.* TO 'conviniuser'@'%';

FLUSH PRIVILEGES;